[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = "symbols"

[package]
name = "snake"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
fastrand = "2.3.0"
ratatui = "0.29.0"
